[general]
import = [
	#"~/.config/alacritty/themes/themes/papertheme.toml",
	"~/.config/alacritty/themes/themes/catppuccin_latte.toml",
	#"~/.config/alacritty/themes/themes/dracula.toml",
	#"~/.config/alacritty/themes/themes/github_light.toml",
	#"~/.config/alacritty/themes/themes/campbell.toml",
	#"~/.config/alacritty/themes/themes/one_light.toml",
	"~/.config/alacritty/my_alacritty.toml",
]
