
[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "2"
XCURSOR_SIZE = "8"

[window]
dynamic_padding = false
decorations = "Full"
startup_mode = "Maximized"
dynamic_title = true
#dimensions = { columns = 80, lines = 24 }
padding = { x = 10, y = 10 }

[scrolling]
# history = 2_500
multiplier = 3

[font]
size = 13.5
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = "Block"
vi_mode_style = "None"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Left", action= "Copy" },
    { mouse = "Middle", action= "PasteSelection" },
    { mouse = "Right", action= "Paste" }
]

[general]
live_config_reload = true
working_directory = "None"

